//
//  GBE, Nick Marino
//
//  MIT LICENSE
//

#ifndef GBE_CMD_H_
#define GBE_CMD_H_

#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct cmd_t {
    char* dsym;
    void* exec;
    byte_t operands;
};

struct cb_t {
    char* dsym;
    void (*exec)(void);
};

extern const struct cmd_t insts[256]; 
extern const struct cb_t extended_insts[256];

void cmd_undefined();
void cmd_nop();
void cmd_ld_bc_nn(byte_t operand);
void cmd_ld_bcp_a();
void cmd_inc_bc();
void cmd_inc_b();
void cmd_dec_b();
void cmd_ld_b_n(byte_t operand);
void cmd_rlca();
void cmd_ld_nnp_sp(word_t operand);
void cmd_add_hl_bc();
void cmd_ld_a_bcp();
void cmd_dec_bc();
void cmd_inc_c();
void cmd_dec_c();
void cmd_ld_c_n(byte_t operand);
void cmd_rrca();
void cmd_stop(byte_t operand);
void cmd_ld_de_nn(word_t operand);
void cmd_ld_dep_a();
void cmd_inc_de();
void cmd_inc_d();
void cmd_dec_d();
void cmd_ld_d_n(byte_t operand);
void cmd_rla();
void cmd_jr_n(byte_t operand);
void cmd_add_hl_de();
void cmd_ld_a_dep();
void cmd_dec_de();
void cmd_inc_e();
void cmd_dec_e();
void cmd_ld_e_n(byte_t operand);
void cmd_rra();
void cmd_jr_nz_n(byte_t operand);
void cmd_ld_hl_nn(word_t operand);
void cmd_ldi_hlp_a();
void cmd_inc_hl();
void cmd_inc_h();
void cmd_dec_h();
void cmd_ld_h_n(byte_t operand);
void cmd_daa();
void cmd_jr_z_n(byte_t operand);
void cmd_add_hl_hl();
void cmd_ldi_a_hlp();
void cmd_dec_hl();
void cmd_inc_l();
void cmd_dec_l();
void cmd_ld_l_n(byte_t operand);
void cmd_cpl();
void cmd_jr_nc_n(byte_t operand);
void cmd_ld_sp_nn(word_t operand);
void cmd_ldd_hlp_a();
void cmd_inc_sp();
void cmd_inc_hlp();
void cmd_dec_hlp();
void cmd_ld_hlp_n(byte_t operand);
void cmd_scf();
void cmd_jr_c_n(byte_t operand);
void cmd_add_hl_sp();
void cmd_ldd_a_hlp();
void cmd_dec_sp();
void cmd_inc_a();
void cmd_dec_a();
void cmd_ld_a_n(byte_t operand);
void cmd_ccf();
void cmd_ld_b_b();
void cmd_ld_b_c();
void cmd_ld_b_d();
void cmd_ld_b_e();
void cmd_ld_b_h();
void cmd_ld_b_l();
void cmd_ld_b_hlp();
void cmd_ld_b_a();
void cmd_ld_c_b();
void cmd_ld_c_c();
void cmd_ld_c_d();
void cmd_ld_c_e();
void cmd_ld_c_h();
void cmd_ld_c_l();
void cmd_ld_c_hlp();
void cmd_ld_c_a();
void cmd_ld_d_b();
void cmd_ld_d_c();
void cmd_ld_d_d();
void cmd_ld_d_e();
void cmd_ld_d_h();
void cmd_ld_d_l();
void cmd_ld_d_hlp();
void cmd_ld_d_a();
void cmd_ld_e_b();
void cmd_ld_e_c();
void cmd_ld_e_d();
void cmd_ld_e_e();
void cmd_ld_e_h();
void cmd_ld_e_l();
void cmd_ld_e_hlp();
void cmd_ld_e_a();
void cmd_ld_h_b();
void cmd_ld_h_c();
void cmd_ld_h_d();
void cmd_ld_h_e();
void cmd_ld_h_h();
void cmd_ld_h_l();
void cmd_ld_h_hlp();
void cmd_ld_h_a();
void cmd_ld_l_b();
void cmd_ld_l_c();
void cmd_ld_l_d();
void cmd_ld_l_e();
void cmd_ld_l_h();
void cmd_ld_l_l();
void cmd_ld_l_hlp();
void cmd_ld_l_a();
void cmd_ld_hlp_b();
void cmd_ld_hlp_c();
void cmd_ld_hlp_d();
void cmd_ld_hlp_e();
void cmd_ld_hlp_h();
void cmd_ld_hlp_l();
void cmd_halt();
void cmd_ld_hlp_a();
void cmd_ld_a_b();
void cmd_ld_a_c();
void cmd_ld_a_d();
void cmd_ld_a_e();
void cmd_ld_a_h();
void cmd_ld_a_l();
void cmd_ld_a_hlp();
void cmd_ld_a_a();
void cmd_add_a_b();
void cmd_add_a_c();
void cmd_add_a_d();
void cmd_add_a_e();
void cmd_add_a_h();
void cmd_add_a_l();
void cmd_add_a_hlp();
void cmd_add_a_a();
void cmd_adc_b();
void cmd_adc_c();
void cmd_adc_d();
void cmd_adc_e();
void cmd_adc_h();
void cmd_adc_l();
void cmd_adc_hlp();
void cmd_adc_a();
void cmd_sub_b();
void cmd_sub_c();
void cmd_sub_d();
void cmd_sub_e();
void cmd_sub_h();
void cmd_sub_l();
void cmd_sub_hlp();
void cmd_sub_a();
void cmd_sbc_b();
void cmd_sbc_c();
void cmd_sbc_d();
void cmd_sbc_e();
void cmd_sbc_h();
void cmd_sbc_l();
void cmd_sbc_hlp();
void cmd_sbc_a();
void cmd_and_b();
void cmd_and_c();
void cmd_and_d();
void cmd_and_e();
void cmd_and_h();
void cmd_and_l();
void cmd_and_hlp();
void cmd_and_a();
void cmd_xor_b();
void cmd_xor_c();
void cmd_xor_d();
void cmd_xor_e();
void cmd_xor_h();
void cmd_xor_l();
void cmd_xor_hlp();
void cmd_xor_a();
void cmd_or_b();
void cmd_or_c();
void cmd_or_d();
void cmd_or_e();
void cmd_or_h();
void cmd_or_l();
void cmd_or_hlp();
void cmd_or_a();
void cmd_cp_b();
void cmd_cp_c();
void cmd_cp_d();
void cmd_cp_e();
void cmd_cp_h();
void cmd_cp_l();
void cmd_cp_hlp();
void cmd_cp_a();
void cmd_ret_nz();
void cmd_pop_bc();
void cmd_jp_nz_nn(word_t operand);
void cmd_jp_nn(word_t operand);
void cmd_call_nz_nn(word_t operand);
void cmd_push_bc();
void cmd_add_a_n(byte_t operand);
void cmd_rst_0();
void cmd_ret_z();
void cmd_ret();
void cmd_jp_z_nn(word_t operand);
void cmd_cb(byte_t opcode);
void cmd_call_z_nn(word_t operand);
void cmd_call_nn(word_t operand);
void cmd_adc_n(byte_t operand);
void cmd_rst_08();
void cmd_ret_nc();
void cmd_pop_de();
void cmd_jp_nc_nn(word_t operand);
void cmd_call_nc_nn(word_t operand);
void cmd_push_de();
void cmd_sub_n(byte_t operand);
void cmd_rst_10();
void cmd_ret_c();
void cmd_jp_c_nn(word_t operand);
void cmd_call_c_nn(word_t operand);
void cmd_sbc_n(byte_t operand);
void cmd_rst_18();
void cmd_ld_ff_n_ap(byte_t operand);
void cmd_pop_hl();
void cmd_ld_ff_c_a();
void cmd_push_hl();
void cmd_and_n(byte_t operand);
void cmd_rst_20();
void cmd_add_sp_n(byte_t operand);
void cmd_jp_hl();
void cmd_ld_nnp_a(word_t operand);
void cmd_xor_n(byte_t operand);
void cmd_rst_28();
void cmd_ld_ff_ap_n(byte_t operand);
void cmd_pop_af();
void cmd_ld_a_ff_c();
void cmd_di_inst();
void cmd_push_af();
void cmd_or_n(byte_t operand);
void cmd_rst_30();
void cmd_ld_hl_sp_n(byte_t operand);
void cmd_ld_sp_hl();
void cmd_ld_a_nnp(word_t operand);
void cmd_ei();
void cmd_cp_n(byte_t operand);
void cmd_rst_38();

void cmd_rlc_b();
void cmd_rlc_c();
void cmd_rlc_d();
void cmd_rlc_e();
void cmd_rlc_h();
void cmd_rlc_l();
void cmd_rlc_hlp();
void cmd_rlc_a();
void cmd_rrc_b();
void cmd_rrc_c();
void cmd_rrc_d();
void cmd_rrc_e();
void cmd_rrc_h();
void cmd_rrc_l();
void cmd_rrc_hlp();
void cmd_rrc_a();
void cmd_rl_b();
void cmd_rl_c();
void cmd_rl_d();
void cmd_rl_e();
void cmd_rl_h();
void cmd_rl_l();
void cmd_rl_hlp();
void cmd_rl_a();
void rr_b();
void rr_c();
void rr_d();
void rr_e();
void rr_h();
void rr_l();
void rr_hlp();
void rr_a();
void cmd_sla_b();
void cmd_sla_c();
void cmd_sla_d();
void cmd_sla_e();
void cmd_sla_h();
void cmd_sla_l();
void cmd_sla_hlp();
void cmd_sla_a();
void cmd_sra_b();
void cmd_sra_c();
void cmd_sra_d();
void cmd_sra_e();
void cmd_sra_h();
void cmd_sra_l();
void cmd_sra_hlp();
void cmd_sra_a();
void cmd_swap_b();
void cmd_swap_c();
void cmd_swap_d();
void cmd_swap_e();
void cmd_swap_h();
void cmd_swap_l();
void cmd_swap_hlp();
void cmd_swap_a();
void cmd_srl_b();
void cmd_srl_c();
void cmd_srl_d();
void cmd_srl_e();
void cmd_srl_h();
void cmd_srl_l();
void cmd_srl_hlp();
void cmd_srl_a();
void cmd_bit_0_b();
void cmd_bit_0_c();
void cmd_bit_0_d();
void cmd_bit_0_e();
void cmd_bit_0_h();
void cmd_bit_0_l();
void cmd_bit_0_hlp();
void cmd_bit_0_a();
void cmd_bit_1_b();
void cmd_bit_1_c();
void cmd_bit_1_d();
void cmd_bit_1_e();
void cmd_bit_1_h();
void cmd_bit_1_l();
void cmd_bit_1_hlp();
void cmd_bit_1_a();
void cmd_bit_2_b();
void cmd_bit_2_c();
void cmd_bit_2_d();
void cmd_bit_2_e();
void cmd_bit_2_h();
void cmd_bit_2_l();
void cmd_bit_2_hlp();
void cmd_bit_2_a();
void cmd_bit_3_b();
void cmd_bit_3_c();
void cmd_bit_3_d();
void cmd_bit_3_e();
void cmd_bit_3_h();
void cmd_bit_3_l();
void cmd_bit_3_hlp();
void cmd_bit_3_a();
void cmd_bit_4_b();
void cmd_bit_4_c();
void cmd_bit_4_d();
void cmd_bit_4_e();
void cmd_bit_4_h();
void cmd_bit_4_l();
void cmd_bit_4_hlp();
void cmd_bit_4_a();
void cmd_bit_5_b();
void cmd_bit_5_c();
void cmd_bit_5_d();
void cmd_bit_5_e();
void cmd_bit_5_h();
void cmd_bit_5_l();
void cmd_bit_5_hlp();
void cmd_bit_5_a();
void cmd_bit_6_b();
void cmd_bit_6_c();
void cmd_bit_6_d();
void cmd_bit_6_e();
void cmd_bit_6_h();
void cmd_bit_6_l();
void cmd_bit_6_hlp();
void cmd_bit_6_a();
void cmd_bit_7_b();
void cmd_bit_7_c();
void cmd_bit_7_d();
void cmd_bit_7_e();
void cmd_bit_7_h();
void cmd_bit_7_l();
void cmd_bit_7_hlp();
void cmd_bit_7_a();
void cmd_res_0_b();
void cmd_res_0_c();
void cmd_res_0_d();
void cmd_res_0_e();
void cmd_res_0_h();
void cmd_res_0_l();
void cmd_res_0_hlp();
void cmd_res_0_a();
void cmd_res_1_b();
void cmd_res_1_c();
void cmd_res_1_d();
void cmd_res_1_e();
void cmd_res_1_h();
void cmd_res_1_l();
void cmd_res_1_hlp();
void cmd_res_1_a();
void cmd_res_2_b();
void cmd_res_2_c();
void cmd_res_2_d();
void cmd_res_2_e();
void cmd_res_2_h();
void cmd_res_2_l();
void cmd_res_2_hlp();
void cmd_res_2_a();
void cmd_res_3_b();
void cmd_res_3_c();
void cmd_res_3_d();
void cmd_res_3_e();
void cmd_res_3_h();
void cmd_res_3_l();
void cmd_res_3_hlp();
void cmd_res_3_a();
void cmd_res_4_b();
void cmd_res_4_c();
void cmd_res_4_d();
void cmd_res_4_e();
void cmd_res_4_h();
void cmd_res_4_l();
void cmd_res_4_hlp();
void cmd_res_4_a();
void cmd_res_5_b();
void cmd_res_5_c();
void cmd_res_5_d();
void cmd_res_5_e();
void cmd_res_5_h();
void cmd_res_5_l();
void cmd_res_5_hlp();
void cmd_res_5_a();
void cmd_res_6_b();
void cmd_res_6_c();
void cmd_res_6_d();
void cmd_res_6_e();
void cmd_res_6_h();
void cmd_res_6_l();
void cmd_res_6_hlp();
void cmd_res_6_a();
void cmd_res_7_b();
void cmd_res_7_c();
void cmd_res_7_d();
void cmd_res_7_e();
void cmd_res_7_h();
void cmd_res_7_l();
void cmd_res_7_hlp();
void cmd_res_7_a();
void cmd_set_0_b();
void cmd_set_0_c();
void cmd_set_0_d();
void cmd_set_0_e();
void cmd_set_0_h();
void cmd_set_0_l();
void cmd_set_0_hlp();
void cmd_set_0_a();
void cmd_set_1_b();
void cmd_set_1_c();
void cmd_set_1_d();
void cmd_set_1_e();
void cmd_set_1_h();
void cmd_set_1_l();
void cmd_set_1_hlp();
void cmd_set_1_a();
void cmd_set_2_b();
void cmd_set_2_c();
void cmd_set_2_d();
void cmd_set_2_e();
void cmd_set_2_h();
void cmd_set_2_l();
void cmd_set_2_hlp();
void cmd_set_2_a();
void cmd_set_3_b();
void cmd_set_3_c();
void cmd_set_3_d();
void cmd_set_3_e();
void cmd_set_3_h();
void cmd_set_3_l();
void cmd_set_3_hlp();
void cmd_set_3_a();
void cmd_set_4_b();
void cmd_set_4_c();
void cmd_set_4_d();
void cmd_set_4_e();
void cmd_set_4_h();
void cmd_set_4_l();
void cmd_set_4_hlp();
void cmd_set_4_a();
void cmd_set_5_b();
void cmd_set_5_c();
void cmd_set_5_d();
void cmd_set_5_e();
void cmd_set_5_h();
void cmd_set_5_l();
void cmd_set_5_hlp();
void cmd_set_5_a();
void cmd_set_6_b();
void cmd_set_6_c();
void cmd_set_6_d();
void cmd_set_6_e();
void cmd_set_6_h();
void cmd_set_6_l();
void cmd_set_6_hlp();
void cmd_set_6_a();
void cmd_set_7_b();
void cmd_set_7_c();
void cmd_set_7_d();
void cmd_set_7_e();
void cmd_set_7_h();
void cmd_set_7_l();
void cmd_set_7_hlp();
void cmd_set_7_a();

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // GBE_CMD_H_
